Version: apps/v1
kind: Deployment
metadata:
  name: react-client-deployment
  labels:
    app: react-client
spec:
  replicas: 1 #The number of pods to be created in the 
   #Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: react-client
  template:
    metadata:
      labels:
        app: react-client
    spec:
      containers:
      - name: react-client #The name of the react.js application container
        #The Docker image for building the React.js application container
        image: 9h4f263p.c1.va1.container-registry.ovh.us/maigha/qrclient:07-Jun-5
        ports:
        - containerPort: 3000 #The port for the React.js application container
